services:
  otel-collector:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    container_name: otel-collector
    ports:
      - "4317:4317"
    env_file:
      - .env
    volumes:
      - ./dc-collector-config.yaml:/etc/collector-config.yaml:ro
      - ~/.aws:/root/.aws:ro
    command: ["--config", "/etc/collector-config.yaml"]
    # restart: unless-stopped
    networks:
      - tracing

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fast-api-app
    env_file:
      - .env
    environment:
      XRAY_ENDPOINT: http://otel-collector:4317
      IMAGE: docker-compose-image
    depends_on:
      - otel-collector
    ports:
      - "8000:3000"
    networks:
      - tracing

networks:
  tracing:
    driver: bridge
