services:
  otel-collector:
    build:
      context: .
      dockerfile: Dockerfile
      target: collector
    container_name: otel-collector
    ports:
      - "4317:4317"
    environment:
      OTEL_ENDPOINT: otel-collector:4317
    env_file:
      - .env
    volumes:
      - ~/.aws:/root/.aws:ro
    networks:
      - tracing

  app-caller:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-caller
    container_name: app-caller
    env_file:
      - .env
    environment:
      AWS_XRAY_ENDPOINT: http://otel-collector:4317
      AWS_SERVICE_NAME: local-caller
      IMAGE: docker-compose-app-caller
      DOWNSTREAM_URL: http://app-responder:3000/responder
    volumes:
      - ./src:/usr/app/app
    command: uvicorn app.caller.app:app --host 0.0.0.0 --port 3000 --reload
    depends_on:
      - otel-collector
      - app-responder
    ports:
      - "8000:3000"
    networks:
      - tracing

  app-responder:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-responder
    container_name: app-responder
    env_file:
      - .env
    environment:
      AWS_XRAY_ENDPOINT: http://otel-collector:4317
      AWS_SERVICE_NAME: local-responder
      IMAGE: docker-compose-app-responder
      ROOT_PATH: /responder
    volumes:
      - ./src:/usr/app/app
    command: uvicorn app.responder.app:app --host 0.0.0.0 --port 3000 --reload
    depends_on:
      - otel-collector
    ports:
      - "8001:3000"
    networks:
      - tracing

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
      target: consumer
    container_name: consumer
    env_file:
      - .env
    environment:
      AWS_XRAY_ENDPOINT: http://otel-collector:4317
      AWS_SERVICE_NAME: local-consumer
      IMAGE: docker-compose-app-consumer
    volumes:
      - ./src:/usr/app/app
    command: python -u consumer/app.py
    depends_on:
      - otel-collector
    networks:
      - tracing

  debug:
    build:
      context: .
      dockerfile: Dockerfile
      target: debug
    container_name: debug-tool
    depends_on:
      - app-caller
      - app-responder
    networks:
      - tracing

networks:
  tracing:
    driver: bridge
