services:
  xray-daemon:
    image: amazon/aws-xray-daemon:latest
    container_name: xray-daemon
    ports:
      - "2000:2000/udp"
    env_file:
      - .env
    volumes:
      - ~/.aws:/root/.aws:ro
    command: ["-o"]
    # restart: unless-stopped
    networks:
      - tracing

  otel-collector:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    container_name: otel-collector
    ports:
      - "4317:4317"
    env_file:
      - .env
    volumes:
      - ./collector-config.yaml:/etc/collector-config.yaml:ro
      - ~/.aws:/root/.aws:ro
    command: ["--config", "/etc/collector-config.yaml"]
    # restart: unless-stopped
    networks:
      - tracing

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: fast-api-app
  #   env_file:
  #     - .env
  #   environment:
  #     AWS_XRAY_ENDPOINT: http://xray-daemon:2000
  #     IMAGE: your-image-name
  #   depends_on:
  #     - xray-daemon
  #   ports:
  #     - "8000:3000"
  #   networks:
  #     - tracing

networks:
  tracing:
    driver: bridge
