on:
  workflow_call:
    inputs:
      environment:
        description: environment reference i.e. 'prod' or 'dev'
        required: true
        type: string
      infra_version:
        description: "Version of infrastructure (terraform) to be deployed"
        required: true
        type: string
      app_responder_image_uri:
        required: true
        type: string
        description: Image to be deployed to ECS
      app_caller_image_uri:
        required: true
        type: string
        description: Image to be deployed to ECS
      aws_otel_collector_image_uri:
        required: true
        type: string
        description: Image to be deployed to ECS
      debug_image_uri:
        required: true
        type: string
        description: Image to be deployed to ECS


concurrency: # only run one instance of workflow at any one time
  group: ${{ github.workflow }}-${{ inputs.environment }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write

env:
  AWS_OIDC_ROLE_ARN: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/ecs-internal-service-${{ inputs.environment }}-github-oidc-role

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.infra_version }}

      - uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/oidc

      - uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/security

  cluster:
    needs:
      - setup
    runs-on: ubuntu-latest
    outputs:
      cluster_name: ${{ steps.get-cluster.outputs.cluster_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.infra_version }}

      - uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        id: cluster
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/cluster

      - name: get cluster
        id: get-cluster
        env:
          TG_OUTPUTS: ${{ steps.cluster.outputs.tg_outputs  }}
        run: |
          echo "cluster_name=$(echo $TG_OUTPUTS | jq -r '.cluster_name.value')" >> $GITHUB_OUTPUT

  network:
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.infra_version }}

      - uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        id: cluster
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/network

  task-responder:
    needs: setup
    runs-on: ubuntu-latest
    outputs:
      task_definition_arn: ${{ steps.get-task.outputs.task_definition_arn }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.infra_version }}

      - uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        id: task
        env: 
          TF_VAR_image_uri: ${{ inputs.app_responder_image_uri }}
          TF_VAR_aws_otel_collector_image_uri: ${{ inputs.aws_otel_collector_image_uri }}
          TF_VAR_debug_image_uri: ${{ inputs.debug_image_uri }}
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/task-responder

      - name: get task
        id: get-task
        env:
          TG_OUTPUTS: ${{ steps.task.outputs.tg_outputs  }}
        run: |
          echo "task_definition_arn=$(echo $TG_OUTPUTS | jq -r '.task_definition_arn.value')" >> $GITHUB_OUTPUT

  ecs-responder-svc:
    needs:
      - cluster
      - task-responder
    outputs:
      internal_dns: ${{ steps.get-vars.outputs.internal_dns }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.infra_version }}

      - uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        id: ecs-responder-svc
        env:
          TF_VAR_cluster_name: ${{ needs.cluster.outputs.cluster_name }}
          TF_VAR_task_definition_arn: ${{ needs.task-responder.outputs.task_definition_arn }}
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/ecs-responder-svc

      - name: get vars
        id: get-vars
        env:
          TG_OUTPUTS: ${{ steps.ecs-responder-svc.outputs.tg_outputs  }}
        run: |
          echo "internal_dns=$(echo $TG_OUTPUTS | jq -r '.internal_dns.value')" >> $GITHUB_OUTPUT

  task-caller:
    needs: ecs-responder-svc
    runs-on: ubuntu-latest
    outputs:
      task_definition_arn: ${{ steps.get-task.outputs.task_definition_arn }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.infra_version }}

      - uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        id: task
        env: 
          TF_VAR_image_uri: ${{ inputs.app_caller_image_uri }}
          TF_VAR_aws_otel_collector_image_uri: ${{ inputs.aws_otel_collector_image_uri }}
          TF_VAR_debug_image_uri: ${{ inputs.debug_image_uri }}
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/task-caller
          override_tg_vars: '{"additional_env_vars": [{"name": "DOWNSTREAM_URL", "value": "http://${{ needs.ecs-responder-svc.outputs.internal_dns }}"}]}'

      - name: get task
        id: get-task
        env:
          TG_OUTPUTS: ${{ steps.task.outputs.tg_outputs  }}
        run: |
          echo "task_definition_arn=$(echo $TG_OUTPUTS | jq -r '.task_definition_arn.value')" >> $GITHUB_OUTPUT

  ecs-caller-svc:
    needs:
      - cluster
      - task-caller
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.infra_version }}

      - uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        env: 
          TF_VAR_task_definition_arn: ${{ needs.task-caller.outputs.task_definition_arn }}
          TF_VAR_cluster_name: ${{ needs.cluster.outputs.cluster_name }}
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/ecs-caller-svc