name: Kill Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev

concurrency: # only run one instance of workflow at any one time
  group: ${{ github.workflow }}-${{ inputs.environment }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write

env:
  TF_VAR_image_uri: this
  TF_VAR_aws_otel_collector_image_uri: this
  TF_VAR_debug_image_uri: this
  TF_VAR_task_definition_arn: "blah"
  TF_VAR_downstream_url: "http://blah.com"
  AWS_OIDC_ROLE_ARN: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/ecs-internal-service-${{ inputs.environment }}-github-oidc-role

jobs:
  svc-caller:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/service_caller
          tg_action: destroy

  svc-responder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/service_responder
          tg_action: destroy

  svc-consumer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Destroy ecrs
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/service_consumer
          tg_action: destroy

  task-caller:
    needs: svc-caller
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Destroy ecrs
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/task_caller
          tg_action: destroy

  task-responder:
    needs: svc-responder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/task_responder
          tg_action: destroy

  task-consumer:
    needs: 
      - svc-consumer
      - svc-caller
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/task_consumer
          tg_action: destroy

  sqs-consumer:
    needs: task-consumer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/sqs_consumer
          tg_action: destroy

  ecr:
    needs:
      - task-caller
      - task-responder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Destroy ecrs
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/ecr
          tg_action: destroy

  cluster:
    needs:
      - svc-caller
      - svc-responder
      - svc-consumer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/cluster
          tg_action: destroy

  network:
    needs:
      - svc-caller
      - svc-responder
      - svc-consumer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/network
          tg_action: destroy

  security:
    needs:
      - network
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/security
          tg_action: destroy
