name: Kill Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev

concurrency: # only run one instance of workflow at any one time
  group: ${{ github.workflow }}-${{ inputs.environment }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write

env:
  TF_VAR_lambda_version: this
  AWS_OIDC_ROLE_ARN: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/ecs-internal-service-${{ inputs.environment }}-github-oidc-role

jobs:
  ecs-caller-svc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        env: 
          TF_VAR_task_definition_arn: "blah"
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/ecs-caller-svc
          tg_action: destroy

  ecs-responder-svc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        env: 
          TF_VAR_task_definition_arn: "blah"
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/ecs-responder-svc
          tg_action: destroy

  task-caller:
    needs: ecs-caller-svc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Destroy ecrs
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        env: 
          TF_VAR_image_uri: this
          TF_VAR_aws_otel_collector_image_uri: this
          TF_VAR_debug_image_uri: this
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/task-caller
          tg_action: destroy

  task-responder:
    needs: ecs-responder-svc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Destroy ecrs
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        env: 
          TF_VAR_image_uri: this
          TF_VAR_aws_otel_collector_image_uri: this
          TF_VAR_debug_image_uri: this
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/task-responder
          tg_action: destroy

  ecr:
    needs:
      - task-caller
      - task-responder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Destroy ecrs
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/ecr
          tg_action: destroy

  cluster:
    needs:
      - ecs-caller-svc
      - ecs-responder-svc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/cluster
          tg_action: destroy

  network:
    needs:
      - ecs-caller-svc
      - ecs-responder-svc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.0
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/network
          tg_action: destroy
